/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.IOException;

import static java.lang.System.exit;

/**
 *
 * @author rispas
 */
public class game extends javax.swing.JFrame {

    String str;
    String empty_task = "----------";
    int pointer;
    /**
     * Creates new form NewJFrame
     */
    public game() {
        initComponents();
        pointer =1;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        task_field = new javax.swing.JTextField();
        complete_button = new javax.swing.JButton();
        task1 = new javax.swing.JLabel();
        task2 = new javax.swing.JLabel();
        task3 = new javax.swing.JLabel();
        task4 = new javax.swing.JLabel();
        task5 = new javax.swing.JLabel();
        task6 = new javax.swing.JLabel();
        task7 = new javax.swing.JLabel();
        task8 = new javax.swing.JLabel();
        task9 = new javax.swing.JLabel();
        task10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mana_value_label = new javax.swing.JLabel();
        mana_value_field = new javax.swing.JTextField();
        wood_value_label = new javax.swing.JLabel();
        wood_value_field = new javax.swing.JTextField();
        food_value_label = new javax.swing.JLabel();
        food_value_field = new javax.swing.JTextField();
        pop_value_label = new javax.swing.JLabel();
        pop_value_field = new javax.swing.JTextField();
        cabin_button = new javax.swing.JButton();
        farm_button = new javax.swing.JButton();
        homes_button = new javax.swing.JButton();
        hall_button = new javax.swing.JButton();
        deposit_button = new javax.swing.JButton();
        church_button = new javax.swing.JButton();
        stocks_button = new javax.swing.JButton();
        cabin_label = new javax.swing.JLabel();
        deposit_label = new javax.swing.JLabel();
        farm_label = new javax.swing.JLabel();
        stocks_label = new javax.swing.JLabel();
        cabin_value_label = new javax.swing.JLabel();
        deposits_value_label = new javax.swing.JLabel();
        farms_value_label = new javax.swing.JLabel();
        stocks_value_label = new javax.swing.JLabel();
        pop_cap_label = new javax.swing.JLabel();
        church_label = new javax.swing.JLabel();
        hall_label = new javax.swing.JLabel();
        pop_cap_value_label = new javax.swing.JLabel();
        church_level_label = new javax.swing.JLabel();
        hall_level_label = new javax.swing.JLabel();
        save_button = new javax.swing.JButton();
        Help = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        task_field.setText("Enter a task");
        task_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_fieldActionPerformed(evt);
            }
        });

        complete_button.setText("Complete Task!");
        complete_button.setAutoscrolls(true);
        complete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complete_buttonActionPerformed(evt);
            }
        });

        task1.setText("-----------------");

        task2.setText("-----------------");

        task3.setText("-----------------");

        task4.setText("-----------------");

        task5.setText("-----------------");

        task6.setText("-----------------");

        task7.setText("-----------------");

        task8.setText("-----------------");

        task9.setText("-----------------");

        task10.setText("-----------------");

        mana_value_label.setForeground(new java.awt.Color(0, 153, 255));
        mana_value_label.setText("Mana:");

        mana_value_field.setEditable(false);
        mana_value_field.setForeground(new java.awt.Color(0, 153, 255));
        mana_value_field.setText("Mana Value");
        mana_value_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mana_value_fieldActionPerformed(evt);
            }
        });

        wood_value_label.setForeground(new java.awt.Color(204, 102, 0));
        wood_value_label.setText("Wood:");

        wood_value_field.setEditable(false);
        wood_value_field.setForeground(new java.awt.Color(204, 102, 0));
        wood_value_field.setText("Wood value");
        wood_value_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wood_value_fieldActionPerformed(evt);
            }
        });

        food_value_label.setForeground(new java.awt.Color(0, 204, 0));
        food_value_label.setText("Food");

        food_value_field.setEditable(false);
        food_value_field.setForeground(new java.awt.Color(0, 204, 0));
        food_value_field.setText("Food value");

        pop_value_label.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        pop_value_label.setForeground(new java.awt.Color(0, 102, 102));
        pop_value_label.setText("POPULATION:");

        pop_value_field.setEditable(false);
        pop_value_field.setForeground(new java.awt.Color(0, 102, 102));
        pop_value_field.setText("pop");

        cabin_button.setForeground(new java.awt.Color(204, 102, 0));
        cabin_button.setText("Cabins");
        cabin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabin_buttonActionPerformed(evt);
            }
        });

        farm_button.setForeground(new java.awt.Color(0, 204, 0));
        farm_button.setText("Farms");
        farm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farm_buttonActionPerformed(evt);
            }
        });

        homes_button.setForeground(new java.awt.Color(0, 102, 102));
        homes_button.setText("Villager Homes");
        homes_button.setToolTipText("");
        homes_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homes_buttonActionPerformed(evt);
            }
        });

        hall_button.setForeground(new java.awt.Color(0, 153, 153));
        hall_button.setText("Hall");
        hall_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hall_buttonActionPerformed(evt);
            }
        });

        deposit_button.setForeground(new java.awt.Color(255, 102, 0));
        deposit_button.setText("Deposits");
        deposit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deposit_buttonActionPerformed(evt);
            }
        });

        church_button.setForeground(new java.awt.Color(0, 153, 153));
        church_button.setText("Church");
        church_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                church_buttonActionPerformed(evt);
            }
        });

        stocks_button.setForeground(new java.awt.Color(51, 204, 0));
        stocks_button.setText("Stocks");
        stocks_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stocks_buttonActionPerformed(evt);
            }
        });

        cabin_label.setText("Wood Cabins:");

        deposit_label.setText("Wood cap:");

        farm_label.setText("Farms:");

        stocks_label.setText("Food cap:");

        cabin_value_label.setText(resources.wood_cabins + "(" + resources.cabin_cost + ")");

        deposits_value_label.setText(+ resources.wood_cap + "(" + resources.deposit_cost + ")");

        farms_value_label.setText(resources.farms + "(" + resources.farm_cost + ")");

        stocks_value_label.setText(resources.food_cap + "(" + resources.stock_cost + ")");

        pop_cap_label.setText("Population cap: ");

        church_label.setText("Church Level:");

        hall_label.setText("Hall Level:");

        pop_cap_value_label.setText(resources.pop_cap + "");

        church_level_label.setText(resources.church_level + "(" + resources.church_cost + ")");

        hall_level_label.setText(resources.hall_level + "(" + resources.hall_level*30 + ")");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(mana_value_label)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(mana_value_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(wood_value_label)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(wood_value_field, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(food_value_label))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(pop_value_label)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(pop_value_field, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(food_value_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(deposit_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(deposits_value_label))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cabin_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cabin_value_label)
                                                .addGap(158, 158, 158)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(pop_cap_label)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(pop_cap_value_label))
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(hall_label)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(hall_level_label))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(church_label)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(church_level_label)))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(deposit_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cabin_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(hall_button)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                                                .addComponent(church_button))
                                                        .addComponent(homes_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(stocks_button)
                                                        .addComponent(farm_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(farm_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(farms_value_label))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(stocks_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(stocks_value_label)))
                                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mana_value_label)
                                        .addComponent(mana_value_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(wood_value_label)
                                        .addComponent(wood_value_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(food_value_label)
                                        .addComponent(food_value_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pop_value_label)
                                        .addComponent(pop_value_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cabin_label)
                                        .addComponent(cabin_value_label)
                                        .addComponent(pop_cap_label)
                                        .addComponent(pop_cap_value_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deposit_label)
                                        .addComponent(deposits_value_label)
                                        .addComponent(church_label)
                                        .addComponent(church_level_label))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(farm_label)
                                        .addComponent(farms_value_label)
                                        .addComponent(hall_label)
                                        .addComponent(hall_level_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(stocks_label)
                                        .addComponent(stocks_value_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cabin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(farm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(homes_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deposit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hall_button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(church_button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stocks_button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49))
        );

        save_button.setText("Save/Exit");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    save_buttonActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        Help.setText("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(task10)
                                                        .addComponent(task9)
                                                        .addComponent(task8)
                                                        .addComponent(task7)
                                                        .addComponent(task6)
                                                        .addComponent(task5)
                                                        .addComponent(task4)
                                                        .addComponent(task3)
                                                        .addComponent(task2)
                                                        .addComponent(task1)
                                                        .addComponent(task_field, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(33, 33, 33))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Help)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(save_button))
                                                        .addComponent(complete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(task_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(task1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(task2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(task3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(task4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(task5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(task6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(task7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(task8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(task9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(task10)
                                .addGap(18, 18, 18)
                                .addComponent(complete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(save_button)
                                        .addComponent(Help))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void task_fieldActionPerformed(java.awt.event.ActionEvent evt) { //BUG_task_pointer: pointer is ahead of list
        // TODO add your handling code here:
        if (pointer <= 10) {
            str = task_field.getText();
            switch (pointer) {
                case 1:
                    task1.setText(str);
                    break;
                case 2:
                    task2.setText(str);
                    break;
                case 3:
                    task3.setText(str);
                    break;
                case 4:
                    task4.setText(str);
                    break;
                case 5:
                    task5.setText(str);
                    break;
                case 6:
                    task6.setText(str);
                    break;
                case 7:
                    task7.setText(str);
                    break;
                case 8:
                    task8.setText(str);
                    break;
                case 9:
                    task9.setText(str);
                    break;
                case 10:
                    task10.setText(str);
                    break;
            }
            pointer = pointer + 1;
        }
    }

    private void complete_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        pointer = pointer - 1;
        if(pointer >= 1) {
            switch (pointer) {
                case 1:
                    task1.setText(empty_task);
                    break;
                case 2:
                    task2.setText(empty_task);
                    break;
                case 3:
                    task3.setText(empty_task);
                    break;
                case 4:
                    task4.setText(empty_task);
                    break;
                case 5:
                    task5.setText(empty_task);
                    break;
                case 6:
                    task6.setText(empty_task);
                    break;
                case 7:
                    task7.setText(empty_task);
                    break;
                case 8:
                    task8.setText(empty_task);
                    break;
                case 9:
                    task9.setText(empty_task);
                    break;
                case 10:
                    task10.setText(empty_task);
                    break;
            }
            resources.increment_mana();
            resources.increment_wood();
            resources.increment_food();
            update_mana();
            update_wood();
            update_food();
        }
    }

    private void mana_value_fieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void homes_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        resources.buy_homes();
        pop_value_field.setText(resources.pop_value+"");
    }

    private void cabin_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        resources.buy_wood_cabins();
        cabin_value_label.setText(resources.wood_cabins + "(" + resources.cabin_cost + ")");
        update_mana();

    }

    private void farm_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        resources.buy_farms();
        farms_value_label.setText(resources.farms + "(" + resources.farm_cost + ")");
        update_mana();
    }

    private void deposit_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        resources.buy_wood_deposit();
        deposits_value_label.setText(resources.wood_cap + "(" + resources.deposit_cost + ")");
    }

    private void hall_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        resources.buy_hall();
        hall_level_label.setText(resources.hall_level+"");
    }

    private void church_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        resources.buy_church();
        church_level_label.setText(resources.church_level + "(" + resources.church_cost + ")");
    }

    private void stocks_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        resources.buy_food_stocks();
        stocks_value_label.setText(resources.food_cap + "(" + resources.stock_cost + ")");
    }

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        // TODO add your handling code here:

        save_controller.save_game();
        exit(0);
    }

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    private void wood_value_fieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void increment_loop(){
        while(true){
            update_wood();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */


        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new landing().setVisible(true);


            }


        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton Help;
    private javax.swing.JButton cabin_button;
    private javax.swing.JLabel cabin_label;
    private javax.swing.JLabel cabin_value_label;
    private javax.swing.JButton church_button;
    private javax.swing.JLabel church_label;
    private javax.swing.JLabel church_level_label;
    private javax.swing.JButton complete_button;
    private javax.swing.JButton deposit_button;
    private javax.swing.JLabel deposit_label;
    private javax.swing.JLabel deposits_value_label;
    private javax.swing.JButton farm_button;
    private javax.swing.JLabel farm_label;
    private javax.swing.JLabel farms_value_label;
    private javax.swing.JTextField food_value_field;
    private javax.swing.JLabel food_value_label;
    private javax.swing.JButton hall_button;
    private javax.swing.JLabel hall_label;
    private javax.swing.JLabel hall_level_label;
    private javax.swing.JButton homes_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mana_value_field;
    private javax.swing.JLabel mana_value_label;
    private javax.swing.JLabel pop_cap_label;
    private javax.swing.JLabel pop_cap_value_label;
    private javax.swing.JTextField pop_value_field;
    private javax.swing.JLabel pop_value_label;
    private javax.swing.JButton save_button;
    private javax.swing.JButton stocks_button;
    private javax.swing.JLabel stocks_label;
    private javax.swing.JLabel stocks_value_label;
    private javax.swing.JLabel task1;
    private javax.swing.JLabel task10;
    private javax.swing.JLabel task2;
    private javax.swing.JLabel task3;
    private javax.swing.JLabel task4;
    private javax.swing.JLabel task5;
    private javax.swing.JLabel task6;
    private javax.swing.JLabel task7;
    private javax.swing.JLabel task8;
    private javax.swing.JLabel task9;
    private javax.swing.JTextField task_field;
    private javax.swing.JTextField wood_value_field;
    private javax.swing.JLabel wood_value_label;
    // End of variables declaration


    public void update_mana(){
        mana_value_field.setText(resources.mana_value +"");
    }

    public void update_wood(){

        wood_value_field.setText(resources.wood_value+"");
    }

    public void update_food(){

        food_value_field.setText(resources.food_value+"");
    }
}


